### ISSUE TITLE
GP marginal likelihood distribution

### ISSUE THREAD

**Issue by bhattsamir** [greta-dev/greta#113]
Hi

(You must have this in greta.gp) would you be willing to add the marginal likelihood for a gp to the distribution list?

This would allow users to use their own covariance matrix in greta rather than choosing a kernel as in greta.gp.

Maybe you already have this?

**Comment by goldingn** [comment]
I'm not sure exactly what you mean - do you mean the multivariate normal density, or an approximation to the marginal likelihood for a given link function, under some approximate inference scheme (Laplace etc.)?

So far with greta.gp I've only used MCMC to do the marginalisation - it isn't calculated directly. I am planning to generalise greta.gp (removing the GPflow dependency) so that anyone can write their own kernel function. The code in greta.gp::gp is pretty simple, so it would could just provide an example of how to build a GP from scratch?

**Comment by bhattsamir** [comment]
right sorry not being clear,

I had this in mind with the optimisation wing of greta where users might create a covariance matrix and then optimise the log marginal likelihood.

However, on second reflection this does seem rather specific and not worth adding

**Comment by goldingn** [comment]
OK cool, makes sense.

Maybe deterministic approximations to the marginal likelihood would be a potential extension for greta.gp?

Closing here, but feel free to open over there if you want!
