### ISSUE TITLE
Missing values in Greta

### ISSUE THREAD

**Issue by kkmann** [greta-dev/greta#117]
Hey, 

what's the current recommended way of treating missing values in Greta? Are you planning to allow partially observed stochastic nodes in Greta? It would be amazing if you manage to get discrete parameters + user-friendly handling of missing values in Greta.

Best,

Kevin

**Comment by goldingn** [comment]
Hey Kevin,

Hmmm, this isn't something I've given much thought to, it's a good point.

It's not functionality I ever really used in my short JAGS career, but if I understand it correctly, if there are NAs in (otherwise) observed stochastics, JAGS will A) skip them when evaluating the likelihood and B) return posterior samples for them, by sampling from the observation model, given each posterior sample of the parameters of the observation model.

Is that right, or does it do something else?

I don't think either of those would present a technical difficulty to implementation. Really it's a design/API issue as to whether this can and should be how greta would work.

My hesitation with A) is that users could accidentally have some data values as NAs (due to some data processing error), and the model would silently run and give the wrong result. I quite like the fact that greta warns early when users try to coerce data to greta arrays (explicitly via `as_data()` or implicitly when combining it with another greta array), since it ensures the data is 'clean' and helps users to define bugs.
I suppose we could have the best of both worlds, if that erroring is relaxed for NAs in observed stochastics (defined using `distribution()`), but instead the user is warned or somehow notified that there are missing values that won't be used for inference.

I'm not sure how B) would work with the greta set up of explicitly stating the things you want to trace. I'm adding an `evaluate()` function that lets you get posterior samples for other parameters or dependent nodes even after running a sampler that wasn't tracing those greta arrays.
I'm not sure what syntax/behaviour could be used to return the missing values specifically.

That was a bit of a stream of consciousness, but I'd be really interested to hear what you think a nice interface would be for handling missing values in greta!

**Comment by kkmann** [comment]
Sorry for the late response. There are quite extensive debates between the JAGS/STAN guys on the issue and I share most of the critique about the automatic handling of missing values in JAGS where no distinction between data and parameters is made on the implementational level (data are just parameters on which you condition). I was just hoping that it might be possible to declare a model in Greta entirely based on stochastic nodes and handle incomplete data by conditioning some stochastic nodes on the (partially) observed data. The idea is really to declare a complete joint model for covariates, latent variables/parameters, and outcomes and to just condition on whatever data has been observed. This enables handling of most missing not at random scenarios and would be a great plus.

Alternatively, it might also be nice to implement a fully conditional approach to handling missing data. This is often more convenient than specifying a joint distribution but the theoretical properties are not yet entirely clear (at least not that I knew, cf. Buuren S, Groothuis-Oudshoorn K. mice: Multivariate imputation by chained equations in R. Journal of statistical software. 2011;45(3). for the R package).

**Comment by kkmann** [comment]
Hey Nick,

have you had the chance to give the whole `missing values' issue some thought? I guess the problem for me is, that there is no notion of conditioning in Greta so far. What I would like to do is specifying a joint distribution via a generative greta model (essentially only using tensorflow variables and distributions) and then treat data input as conditioning the model on the data.

The technical challenge thus is that one would need the notion of a node in the computation graph which is part data (the observed data on which one conditions) and part variable (the entries which are missing). Having to splice this together manually is my main problem with Stan for example. Do you feel that such a thing would be possible within Greta? You could then essentially define an entire generative model and simply condition on any data observed for inference.

**Comment by goldingn** [comment]
Hi Kevin,

I'm still not entirely clear what this would look and behave like. I've never used the missing data functionality in JAGS, and have never faced a problem where it wasn't easier to split the training and prediction data, so I'm feeling (and probably being) a bit dense!

Here's a wireframe of what I think you're imagining, could you tell me if I am close?

1. Coerce a vector of partially-missing data to a greta array
```r
set.seed(1)
x_ <- rnorm(10)
missing <- c(3, 5, 7)
x_[missing] <- NA

library(greta)
x <- as_data(x_)
x
```
> ```
> greta array (partially-missing data)
> 
>             [,1]
>  [1,] -0.6264538
>  [2,]  0.1836433
>  [3,]          ?
>  [4,]  1.5952808
>  [5,]          ?
>  [6,] -0.8204684
>  [7,]          ?
>  [8,]  0.7383247
>  [9,]  0.5757814
> [10,] -0.3053884
```

2. build & fit a model where the data is observed
```r
mu <- normal(0, 1)
sigma <- lognormal(0, 1)
distribution(x) <- normal(mu, sigma)
m <- model(mu, sigma, x[missing])
draws <- mcmc(m)
```

This would then produce draws of the missing values of x, as well as the model parameters.

In this case you would of course get better draws for the missing values from independently sampling post-hoc. Is that what you're after? Just a convenient syntax for these cases? Or is there a case where that's not trivial and the sampler would do something different?

How would you expect greta to handle partially-missing data greta arrays that are then used as independent data? I.e.:
```r
mu <- normal(0, 1)
y <- mu * x
m <- model(y, mu, x[missing])
```
Would you require the user to specify the prior & support of the missing values when coercing them?

**Comment by kkmann** [comment]
Hey Nick,

I think your example is too simple to see my point. I think it is important to keep the different missingness mechanisms in mind. In your example, you implicitly assume missing completely at random (MCAR), i.e., we assume that there is a stochastic model for the missing values and their distribution is independent of all observed variables (here we only have x). Under MCAR, complete case inference is indeed unbiased and fine. The data could, however, also be missing not at random (MNAR). This slightly confusing term means that the distributions for missing yes/no is not independent of the observed data and might even depend on the not-observed missing values (i.e., here the fact whether a certain x[i] is missing might depend on the (missing) value itself). In this case, the inference about \mu and \sigma will be biased! MNAR is hard to fix in practice though because it can never be verified empirically. Still, it would be nice to be able to specify a model for the missingness mechanism in Greta.

These are the two extreme cases. Most often I assume that my data is missing at random (MAR) which kinda lies in between MCAR and MNAR. MAR means that the distribution of missing yes/no may depend on other observed values in the data set but not on the missing values themselves (which would be MNAR). 

As a simple example consider the linear regression Z ~ X + Y with some missing value in Y. If P[Y[i] = NA] is not independent of X[i], but independent of Y[i] we have MAR. If we now consider Y ~ X and both correlate, we can draw samples for each missing Y[i] and get a less biased estimate of the regression parameters (ideally we would sample from Y ~ X + Z but then the graph would become cyclic, this is the idea of multiple imputation via chained equations. This is more convenient in practice because you only specify a set of conditional distributions without worrying about the existence of a joint distribution but probably more difficult to do as you no longer can represent the model as an acyclic graph). So, these kinds of situations I had in mind and I guess these are the most frequent ones anyway.

Technically, I think the problem is that parameters and data are different classes in Stan an Greta. For inference with missing data under MAR one would like to specify a complete joint distribution over the entire data (in the example: p(x, y, z) and not only p(z | x, y)) and then simply sample from the conditional distribution given whatever data was observed (i.e., posterior). This means that conceptually, parameters and data are the same and missing data are just additional parameters / latent variables in the model. A further advantage of having only "parameter nodes" and treating input data as conditioning would be that you could do conditional inference out of the box (i.e., keep other parameters fixed and see what the model does) as this would be the same as providing "data" for said parameter.

**Comment by goldingn** [comment]
OK cool, that's helpful - thanks!

I think something like this is very achievable. Below is a wireframe of a syntax & behaviour that I think would work well and could be added without too much trouble. Could you please let me know whether you think this would be flexible enough and simple enough for the models you're thinking of?

---

1. Introduce a new greta array type for partially-observed data, defined with `as_partial_data()` or similar. This is distinct from standard and implicit `as_data()` calls and requires extra effort so that new users who forgot to clean out their data don't stumble on a potentially confusing aspect of greta.

```r
x_ <- rnorm(10)
x_[c(2, 5, 7)] <- NA
x <- as_partial_data(x_) 
```

2. An additional requirement of partially-observed data is that they must have distribution statement, i.e.:
```r
distribution(partial) <- normal(mu, sd)
```
This statement adds to the overall log density for the observed data, and replaces the values of missing elements with variables. This combined greta array can then be used as if it were data.

3. The partially observed data `x` cannot be used in an operation or distribution until that distribution statement is made. It will error and remind the user to do so.

--- 

So with this syntax, the model you describe above would be coded as:
```r
n <- 20
X_ <- cbind(1, rnorm(n))
Y_ <- rnorm(n)
missing <- sample.int(n, 5)
Y_[missing] <- NA
Z_ <- rnorm(n)

library (greta)

Y <- as_partial_data(Y_) 
X <- as_data(X_)
Z <- as_data(Z_)

# model for Y
beta_Y <- normal(0, 10, dim = 2)
sigma_Y <- lognormal(0, 1)
mu_Y <- X %*% beta_Y
distribution(Y) <- normal(mu_Y, sigma_Y)

# model for Z
beta_Z <- normal(0, 10, dim = 3)
sigma_Z <- lognormal(0, 1)
mu_Z <- cbind(X, Y) %*% beta_Z
distribution(Z) <- normal(mu_Z, sigma_Z)
```

**Comment by goldingn** [comment]
You can fit the same model now, but it takes 4 more lines of ugly code:

```r

library (greta)

X <- as_data(X_)
Z <- as_data(Z_)

# model for Y
beta_Y <- normal(0, 10, dim = 2)
sigma_Y <- lognormal(0, 1)
mu_Y <- X %*% beta_Y

# Y <- as_partial_data(Y_) 
# distribution(Y) <- normal(mu_Y, sigma_Y)

# treat them separately
Y_missing <- normal(mu_Y[missing], sigma_Y)
Y_observed <- as_data(Y_[!missing])
distribution(Y_observed) <- normal(mu_Y[!missing], sigma_Y)

# combine them
Y <- ones(n)
Y[!missing] <- Y_observed
Y[missing] <- Y_missing

# model for Z
beta_Z <- normal(0, 10, dim = 3)
sigma_Z <- lognormal(0, 1)
mu_Z <- cbind(X, Y) %*% beta_Z
distribution(Z) <- normal(mu_Z, sigma_Z)
```

**Comment by kkmann** [comment]
Yeah! I guess that's exactly what I was looking for. You see, this manual splicing (your last comment) can become quite confusing in a real-world model and creates a lot of boilerplate code...

Now, my only concern is with your proposed implementation. This would mean that there are three basic classes in Greta: variables, data, and partial data. Conceptually, it would be much nicer (and maybe simpler) if there where only variables and you simply "input" data by conditioning on it. 
(let's ignore the intercept...)
```
n <- 20
X_ <- rnorm(n)
Y_ <- X + rnorm(n) # example only makes sense if X, Y not independent
missing <- rbinom(n, 1, 1 / (1 + exp(-X_)) # again, if missingness is completely independent of data, 
                                                                   # nothing can be gained
Z_ <- X_ + Y_ + rnorm(n)
Y_[missing] <- NA

library(greta)

# X
mu_X <- normal(0, 10, dim = 1)
sd_X  <- lognormal(0, 10)
X       <- normal(mu_X, sd_X, dim = 10)

# Y
beta_Y_X <- normal(0, 10)
sd_Y        <- lognormal(0, 10)
mu_Y      <- X * beta_Y_X
Y             <- normal(mu_Y, sd_Y, dim = 10)

# Z 
sd_Z          <- lognormal(0, 10)
beta_Z_XY <- normal(0, 10, dim = 2)
mu_Z         <- beta_Z_XY %*% cbind(X, Y) # hope that works
Z                <- normal(mu_Z, sd_Z, dim = 10)

# that completes an entire model:
m <- model(X, Y, Z, beta_Z_XY, sd_Z)

# sample:
smpl <- mcmc(m, conditional_on = list(X = X_, Y = Y_, Z = Z_)) # note that here, I could also conditional on parameters (e.g. beta_Z_XY)
```

I hope that makes clearer what I had in mind ;) Maybe it would also be a good idea to discuss the whole missing data issue with Michael Betancourt (https://github.com/betanalpha) or Bob Carpenter (https://github.com/bob-carpenter) of the Stan development team.

**Comment by goldingn** [comment]
Cool, glad that works for you! I'll leave it here, on the to-do list for things to get implemented.

I'm not planning to change the API to make everything a variable. If you wanted to go down that route, it actually wouldn't be too hard to fork greta and slap a different API on the front.
