### ISSUE TITLE
Wish Support shinystan

### ISSUE THREAD

**Issue by harryprince** [greta-dev/greta#130]
it seems draws can compatible with bayesplot, can greta result integrate with `shinystan`?

```
library (bayesplot)

mcmc_trace(draws)

```

Wish support shinystan like this: `shinystan::launch_shinystan(draws)`

**Comment by goldingn** [comment]
You can do something pretty close already, this works!

```r
shinystan::launch_shinystan(as.shinystan(draws))
```

It won't show all of the stan-specific information, but you can look at the posterior samples in lots of different ways.

greta outputs MCMC samples in the `mcmc.list` format from the `coda` package. That's the most common format for working with MCMC samples in R, which is why it works automatically with packages like `bayesplot` and [`tidybayes`](https://github.com/mjskay/tidybayes).

The `shinystan` developers have chosen to make `launch_shinystan()` operate on objects of class `shinystan`. However they provide an `as.shinystan()` function to convert `mcmc.list` objects to `shinystan` objects. As for your specific syntax request, the `shinystan` developers could change their code automatically try to run `as.shinystan()` on the object passed to `launch_shinystan()`, though that isn't something that can be done from the greta side.

You could post a feature request with the `shinystan` developers, and see if they'd be interested in implementing it?
