### ISSUE TITLE
Cannot clone greta wiki

### ISSUE THREAD

**Issue by pteetor** [greta-dev/greta#161]
I would like to contribute to the [Examples](https://greta-dev.github.io/greta/example_models.html) section of the *greta* wiki. Unfortunately, I get this error when I try to clone the wiki's repo.

```
$ git clone git@github.com:greta-dev/greta.wiki.git
Cloning into 'greta.wiki'...
fatal: remote error: access denied or repository not exported: /e/nw/ee/f6/7e/136756002/73758247.wiki.git
```

Am I doing something wrong? Or, is the wiki repo not accessible to the general public (of which I am member)?

**Comment by goldingn** [comment]
Hi Paul,

That's great! More examples are sorely needed!

We're not actually using a wiki, which is why that's not working. The website is hosted via github pages from the code repo.

If you clone the whole repo and take a look in vignettes/examples, you'll see there are Rmd files for the two existing examples.

The vignettes are built and rolled into the website using pkgdown and a whole bunch of custom html, css and R code. I suspect pkgdown has moved on sufficiently far that you'll need to have my goldingn fork installed. You should be able to build the whole thing by sourcing `docs/build_website.R` from the package root. 

Let me know if I can help at all!

As you might have seen from the issues, I'm planning a section for longer-form case studies, and trying to keep those examples short and snappy.

Nick

**Comment by pteetor** [comment]
Thanks for the quick response, Nick. I will clone the repo and look at vignettes/examples.

**Comment by goldingn** [comment]
Great! Will close this issue, but please open another one or add to the examples issue.
