### ISSUE TITLE
inconsistency in how normal() handles vector inputs

### ISSUE THREAD

**Issue by jdyen** [greta-dev/greta#185]
The following seems to work: `normal(0, 1, dim = c(10, 1))` and so does `normal(rep(0, 10), 1)` but I get an error if I use `normal(rep(0, 10), 1, dim = c(10, 1))` ("array dimensions should be 10x1, but input dimensions were 10x1, 1x1"). It's pretty obvious where this is coming from but is it necessary?

**Comment by goldingn** [comment]
Hmmm, yeah that's not right, and should be easily fixable. It'll be in here: https://github.com/greta-dev/greta/blob/master/R/utils.R#L117-L191

**Comment by goldingn** [comment]
It's because the dimension checking here is triggered on all inputs, if any are non-scalar: https://github.com/greta-dev/greta/blob/master/R/utils.R#L162

Instead, it should only do these checks on the non-scalar elements. Maybe [this line](https://github.com/greta-dev/greta/blob/master/R/utils.R#L165) just needs to be changed from:
```r
vapply(dim_list,
```
to
```r
vapply(dim_list[!scalars],
```
though it would be good to add a test to check for this behaviour too. The test should be added to this block: https://github.com/greta-dev/greta/blob/master/tests/testthat/test_misc.R#L123-L153

**Comment by jdyen** [comment]
Are the other distributions easily vectorised? e.g. `uniform()`

**Comment by goldingn** [comment]
That fix to the error checking should work for all the distributions.

`uniform()` *should* allow vectorisation in the same way as the other distributions

**Comment by jdyen** [comment]
I assume can be closed now?

**Comment by goldingn** [comment]
yep, closed by #186
