### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by rbmillar** [greta-dev/greta#195]
Hi - I'm getting the following installation error. Any ideas? (Some background - I successfully had greta running a few months ago. After updating python and greta, now seem to be stuck). Thanks.

> packageVersion("greta")
[1] ‘0.2.5’
> install_tensorflow(extra_packages = "tensorflow-probability")
Using r-tensorflow conda environment for TensorFlow installation
Solving environment: ...working... failed

PackagesNotFoundError: The following packages are not available from current channels:

  - tensorflow-probability

**Comment by goldingn** [comment]
Hmm, that's an odd one.

The current release (0.2.5) doesn't require `tensorflow-probability`, though I just tried removing tensorflow, re-installing greta and tensorflow, then running your `install_tensorflow()` code. I didn't get an error.

The dev version doesn't have a distinct version number, so it would display 0.2.5 here too. The dev version does require `tensorflow-probability`, so I'm guessing that's what you're doing. With a fresh install of the dev branch and tensorflow, the code above works fine for me too.

I install python stuff into a virtualenv, it's possible you're using conda, and that `tensorflow-probability` isn't yet available via conda (`tensorflow-probability` is still pre-release, which is why the dev version of greta hasn't yet been released).

That's my guess, but could you please provide a few more details to help me diagnose?

* Is this the dev branch or the current release?
* What's the output of `reticulate::py_config()`
* What's the output of `sessionInfo()`

**Comment by goldingn** [comment]
Ah, I see it says conda in your message (should have looked more carefully before replying with all that!)

I'd suggest you use a virtualenv instead. The easiest way would be to restart your R session, and put: `reticulate::use_virtualenv("r-tensorflow")` at the top of your script, then re-install greta.

This pain-point will be resolved by the time the dev version is released.
