### ISSUE TITLE
Estimatedt Parameters of Multinomial

### ISSUE THREAD

**Issue by saptarshiguha** [greta-dev/greta#229]
Firstly, thanks for reworking the code! What a difference.

```
alpha <- exponential(1)
beta <- dirichlet(t(ones(ncol(a2))))
thetai <- dirichlet(beta*alpha)
distribution(a2)  <- multinomial(apply(a2,1,sum), thetai, n_realisations = nrow(a2))
m <- model(alpha,beta,thetai)
draws <- mcmc(m, n_samples=1000)
```
where a2 is a 116534  x 20 matrix. The above code took 25 mins on a 16 core computer. Impressive.

Here is the first ten rows of the `thetai` estimates from the call to `summary(draws)`.

```
                      Mean            SD      Naive SE Time-series SE
thetai[1,1]  2174.47049717 277.164042490 4.38234829883  2.75754578834
thetai[1,2]   770.33691975  97.973634695 1.54909918141  1.05749886214
thetai[1,3]   354.03911718  44.928634091 0.71038407944  0.38507207702
thetai[1,4]   123.87303106  15.825671753 0.25022584121  0.12788539096
thetai[1,5]    52.28156609   6.870472176 0.10863170339  0.04769010677
thetai[1,6]    22.29750469   2.706186283 0.04278856213  0.05677730955
thetai[1,7]     7.69165205   0.968674693 0.01531609171  0.00845656282
thetai[1,8]     2.76319865   0.256896561 0.00406189128  0.00487009505
thetai[1,9]     1.26546961   0.089351967 0.00141277864  0.00095783834
```

Q1:  My initial thought was that multinomial coefficients (`thetai`) ought be between 0 and 1. But the documentation `stats::dmultinom` says that the `probabilities` are scaled to sum to 1. 
Is that the case here? If i scaled `thetai` values in individual samples, would those be the probability estimates for the multinomial distribution?

Q2: If i wanted the posterior distribution of F(**thetai**),  would i access any one of the chains and use the 1000 rows in the `draws` object?

```
List of 4
 $ 11: 'mcmc' num [1:1000, 1:41] 0.919 0.919 0.919 0.919 0.919 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:1000] "1" "2" "3" "4" ...
  .. ..$ : chr [1:41] "beta[1,1]" "beta[1,2]" "beta[1,3]" "beta[1,4]" ...
  ..- attr(*, "mcpar")= num [1:3] 1 1000 1
 $ 12: 'mcmc' num [1:1000, 1:41] 1.25 1.25 1.25 1.25 1.25 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:1000] "1" "2" "3" "4" ...
  .. ..$ : chr [1:41] "beta[1,1]" "beta[1,2]" "beta[1,3]" "beta[1,4]" ...
  ..- attr(*, "mcpar")= num [1:3] 1 1000 1
 $ 13: 'mcmc' num [1:1000, 1:41] 1.18 1.18 1.18 1.18 1.18 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:1000] "1" "2" "3" "4" ...
  .. ..$ : chr [1:41] "beta[1,1]" "beta[1,2]" "beta[1,3]" "beta[1,4]" ...
  ..- attr(*, "mcpar")= num [1:3] 1 1000 1
 $ 14: 'mcmc' num [1:1000, 1:41] 1.25 1.25 1.25 1.25 1.25 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:1000] "1" "2" "3" "4" ...
  .. ..$ : chr [1:41] "beta[1,1]" "beta[1,2]" "beta[1,3]" "beta[1,4]" ...
  ..- attr(*, "mcpar")= num [1:3] 1 1000 1
 - attr(*, "class")= chr "mcmc.list"
 - attr(*, "model_info")=<environment: 0x11c2cd80>
```

Q3: Can we have a mailing list! I feel this is not an issue but still need help solving this.

Thanks again
Cheers

**Comment by goldingn** [comment]
Q1: yes, that's right. `thetai` is scaled internally in both the dirichlet (as the target variable) and the multinomial (as a parameter) so that they return the correct distributions. If you did `thetai / sum(thetai)` you would recover the probability parameter. That's not ideal behaviour, the variable created by `dirichlet()` should be a simplex (positive, summing to one). That's issue #209 which is on my short-term to do list.

Q2: you would probably want all the draws from all chains. That's a question about the coda package really (greta returns chains in coda's `mcmc.list` format and leaves subsequent processing up to the user), but I think you can just do `as.matrix(draws)` to get a 4000 x 41 matrix of posterior samples.

Q3: I'm planning to set up a discourse forum, in a month or so, at the same time as I release v0.3 and redo the website. Would that work or would you still prefer a mailing list?

**Comment by saptarshiguha** [comment]
Excellent! Thanks much. As i explore the Bayes world, i'm discovering more flexible (compared to dirichlet) priors on p.m.f s
