### ISSUE TITLE
Generate samples after optimization just like posterior predictive

### ISSUE THREAD

**Issue by urchgene** [greta-dev/greta#259]
Hi Nick,

Right now, can you generate samples or simulate the model after optimization has converged by plugging in the parameter estimates ?

This is very useful. I'm guessing it can't be done right now? Am I correct?

Thanks.

Uche.

**Comment by Voltemand** [comment]
Hi Uche, 

To the best of my knowledge this is, as you say, not available right now.  I do think that it would be very cool to have!

What you can do as a workaround (though this may be tedious) is to manually rewrite the model. A (toy) example of this is: 

```R
# Model
x <- rnorm(100, 5, 1) 
mu <- variable() # improper prior
sd <- variable(lower = 0) # improper prior
distribution(x) <- normal(mu, sd)
m <- model(mu, sd)

# optimise to find parameters
opt_res <- opt(m, optimiser = bfgs())
opt_res$par

# Rewritten model
mu <- opt_res$par$mu
sd <- opt_res$par$sd
x <- normal(mu, sd)
m <- model(x)

# we can now (pseudo) sample the first model with the found parameters using mcmc
draws <- mcmc(m)

# check the samples look right
tidy_draws <- tidybayes::tidy_draws(draws)
ggplot2::qplot(tidy_draws$x)
```
Due to nature of the models in greta I think the best way of implementing this feature would be to write a function that automatically does the transformation I have manually illustrated. 

All the best, 
Jeffrey

**Comment by urchgene** [comment]
Hi Jeffrey,

Many thanks for your response and a good example.

This is very useful.

Thanks.

Uche.

**Comment by goldingn** [comment]
Yup, being able to take independent draws from random variables (before or after fitting) would be really useful. It's on the to do list, and detailed in #177.

I'll close this issue as a duplicate, but please reopen if I've misunderstood and it's a different feature you're after.
