### ISSUE TITLE
Missing operations

### ISSUE THREAD

**Issue by Voltemand** [greta-dev/greta#277]
Hi Nick, 

Below is a problem I've experienced while I've been messing around with **greta** models' dags. Sometimes the parameters of a distribution node don't seem to 'pick up' certain operations applied to them. (Sorry for the vagueness - I'm quite confused about whats going on.) 

For example in the reprex below the parameter of the Poisson distribution is an operation of type `matrix multiply` when it should seemingly be a an `exp` operation.  In the dag plot for the model (below) you can see that the `exp` connection is going off and not linking properly to the distribution node. I've also encountered the issue with the `ilogit` transform but curiously `log` seems to work just fine. (!?)

This may not have a large effect on base **greta** but has a large effect on extensions which rely on the model dag being an accurate representation of the model. For example I currently have a partially working greta -> stan code parser which can convert most of the example **greta** models. It's completely defeated by this bug however as the information in the dag simply isn't correct. 

All the best, 
Jeffrey

``` r
library(greta, warn.conflicts = FALSE, quietly = TRUE)

set.seed(42)

data("warpbreaks")
X <- as_data(model.matrix(breaks ~ wool + tension, warpbreaks))
y <- as_data(warpbreaks$breaks)

int <- variable()
coefs <- normal(0, 5, dim = ncol(X) - 1)
beta <- c(int, coefs)

eta <- X %*% beta

distribution(y) <- poisson(exp(eta))

m <- model(int, coefs)

#plot(m)

# poisson distbution node
#m$dag$node_list$node_f89e5558

# the distribution's parameters
#m$dag$node_list$node_f89e5558$parameters

m$dag$node_list$node_f89e5558$parameters[[1]]$operation_name
#> [1] "matrix multiply"
```

<sup>Created on 2019-04-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

![image](https://user-images.githubusercontent.com/34267114/56892898-5b55e180-6ac4-11e9-84c2-a574fb4b1bdf.png)

**Comment by goldingn** [comment]
It's a feature, not a bug! (sort of)

This is the representations thing that skips operations to increase numerical stability. E.g. with Poisson distribution, the density can be calculated with the log of lambda with less risk of numerical under/overflow. The same goes for the Bernoulli distribution with logit probability. The (unassigned) greta array created by `exp(eta)` has eta listed as it's 'log' representation. You can do something like `greta:::get_node(exp(eta))$representations` to see the list of representations a greta array has. When the `exp(eta)` greta array is passed in as the parameter of `poisson()`, that distribution node [checks](https://github.com/greta-dev/greta/blob/master/R/probability_distributions.R#L318-L321) to see if it has a log representation, and [uses that](https://github.com/greta-dev/greta/blob/master/R/probability_distributions.R#L327-L333) instead.

Because the plot method just gets the dag from the nodes, this shows up in the plot as `eta` being passed straight in to `poisson()`. The user can still trace the `exp(eta)` greta array, but the `exp()` isn't required for inference. So the plot represents the computational graph, rather than the generative model.

I say it's sort of a feature, because I agree that's confusing when it appears in the plot. It would be better if the plot method could somehow spot these representations and (by default but optionally) plot as though they didn't exist. Or maybe the same thing could be achieved by making the representations setup work differently, so that it doesn't modify the children/parents of a node.

I'm keen to have the ability for the developers of this package and extensions to be able to do these computational tricks behind the scenes, rather than relying on the user to understand it (like with the `poisson_log()` function in Stan). But yeah, the plotting is an issue, and the architecture isn't as tidy as I'd like it to be.

**Comment by Voltemand** [comment]
Thanks for the explanation Nick, I did wonder whether this was caused by the representations. It is a bit disappointing however as this means that my stan -> greta converter won't work on a large class of greta models. Still, I'll close this issue now.
