### ISSUE TITLE
`plot.greta_model` inconsistent behaviour

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [greta-dev/greta#302]
---

Calling `plot` method on a `greta_model` object returns a `grViz`/`htmlwidget` product of `DiagrammeR` without plotting it. 
Taking into account that typically (from my experience) calls to `plot` result in actual plots being rendered one way or another, overriding `plot` beahviour for `greta_model` objects seems questionable. 

Consider following code chunk:
```r
mdl <- model(args)
plot(mdl)
draws <- mcmc(mdl)
plot(draws)
```
In this scenario, only results of the `mcmc` simulations are rendered as plots, while model graph is preapred, but never displayed. 
In order to actually show the model graph every time the code chunk is run (as part of a script file, not interactively), one should modify it: `print(plot(mdl))`.
The difference between `greta:::plot.greta_model` and `coda:::plot.mcmc.list` may confuse the developers.

It can be benficial to have `plot.greta_model` actually displaying the diagram and invisibly returning the diagram object for future reuse. A seprate method (with a different than `plot` name) can be used to construct model graph without displaying it.

**Comment by goldingn** [comment]
Right, `plot.greta_model` returns a grViz object. The print method for the grViz object is to render the plot (as html) in the default viewer. So the code you have there, which is the expected usage, does produce a plot. The plot is rendered in the viewer rather than the graphics device.

Here's a reproducible example:
```r
library(greta)
x <- normal(0, 1)
mdl <- model(x)
plot(mdl)
draws <- mcmc(mdl)
plot(draws)
```

In RStudio this plots the draws in the 'Plots' pane, and the plots the graph in the 'Viewer' pane. In my terminal it plots the draws in a Quartz pane (the default graphics device) and the graph in my browser (the default viewer). In a chunk in an RStudio R notebook both are rendered inline. In a chunk in an R markdown file knitted to html, both are displayed inline. This is the desired and expected behaviour.

Are you seeing some different behaviour than this? If so, please either post an example that reproduces your problem or, if my code above doesn't render a plot for you, more details of the context in which it is not rendering the graph on your system.

**Comment by Ilia-Kosenkov** [comment]
Never used `Diagrammer` before, just realized that `grViz <- DiagrammeR::render_graph(gr)` at the end of `plot.greta_model` specifically renders the diagram in RStudio's viewer (according to the `DiagrammeR`'s docs). 
Apparently, in other than RStudio IDEs the behaviour differs. Your reprex in my case runs exactly as I described - I get only `mcmc` plot.
However,
```r
library(greta)
x <- normal(0, 1)
mdl <- model(x)
plot(mdl) %>% print
draws <- mcmc(mdl)
plot(draws)
```
gives me a model diagram in the default browser, outside of IDE, which is the desired outcome.

I checked this snippet in plane console - it works the same way, only with extra `print`, so it looks like it behaves properly inside RStudio but not outside.

**Comment by goldingn** [comment]
It works fine for me from a terminal (not RStudio), so it's not just an RStudio thing.

It seems like your viewer is probably fine, but for some reason the standard behaviour (when running in interactive mode) of printing objects is maybe being suppressed on your system.

Can you please provide more details of how you are running this code.

- Which IDE/terminal are you using?
- Which operating system are you using?
- Are you running this code:
	- interactively (line by line) in an R script,
	- sourcing the whole script,
	- or running this code inside a function?
- What is the result of `interactive()`?
- What is the result of `getOption("browser")`?
- What is the result of `getOption("viewer")`?

**Comment by Ilia-Kosenkov** [comment]
- VisualStudio 2017 (and `PowerShell Core 7.0.0-preview.1` for console-only test)
- Win10 x64 1903 (18362.207)
- Running as script (i.e. through `source(path)`). 
     - In global env (script file contains only reprex greta code)
     - Inside a function, which is called in script file, result is the same
- `interactive()` is `TRUE` in both cases
- `getOption("viewer")` is `NULL` in both cases
- `getOption("browser")` is `NULL` in the console, but is set to 
```r
function (url) 
{
    rtvs:::send_notification("!WebBrowser", url)
}
<environment: namespace:rtvs>
``` 
in VS, which is expected.

I have just installed a fresh version of `R` few days ago, so apart from installing packages, made no changes to the environment and options.
```
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          6.1                         
year           2019                        
month          07                          
day            05                          
svn rev        76782                       
language       R                           
version.string R version 3.6.1 (2019-07-05)
nickname       Action of the Toes  
```

**Comment by goldingn** [comment]
Thanks for that.

This makes sense. If you are sourcing the script rather than running it interactively, it doesn't automatically print objects that are on their own line, which is the usual behaviour when run interactively.

I think you can do `source(file, print.eval = TRUE)` to make it automatically print and therefore render the plot. Would you mind trying that?

The reliance on default printing (rather than forcing the printing inside `plot.greta_array()`) is unfortunately necessary to make this work with Rmarkdown.

**Comment by Ilia-Kosenkov** [comment]
There is no problem with adding extra `print` or something like that, I just thought it was weird that `plot` behaviour for `greta_model` differs. 

If such behaviour is requried for something else (like `Rmarkdown` compatibility), then it is ok and the issue is resolved. 
Thank you for clarification.

**Comment by goldingn** [comment]
Cool, thank you!
