### ISSUE TITLE
Adding greta example of hierarchical model with correlated varying coefficients

### ISSUE THREAD

**Issue by lionel68** [greta-dev/greta#321]
Based on the [forum](https://forum.greta-stats.org/t/how-to-use-lkj-prior/175) question I put together a greta example Rmd file over [here](https://github.com/lionel68/greta/blob/master/inst/examples/hierarchical_linear_slopes_corr.Rmd), using the iris dataset like in the other hierarchical examples on the page. Note that when fitting the model (calling mcmc), the trace plot look pretty bad, maybe I forgot some things in the model code ...

If I receive the green light I'll be happy to open a pull request.

**Comment by goldingn** [comment]
Awesome, yes please open a PR! I'm not sure why sampling is bad, but I'll have a think about it.

And sorry for taking so long. I have some time to focus on greta now :)

**Comment by goldingn** [comment]
I suspect the poor sampling is because with only three levels (species) Omega and tau are poorly identified, which leads to a slightly knotty posterior. NUTS would probably handle that better than static HMC (should have something NUTS-like as the default soon). Increasing the number of HMC leapfrog steps seems to help, as does increasing the number of chains (due to shared tuning of the stepsize hyperparameter). In any case, not something that should change the code for this example.
