### ISSUE TITLE
print, summary methods for greta_mcmc_list objects

### ISSUE THREAD

**Issue by jeffreypullin** [greta-dev/greta#333]
Hi Nick, 

As previously discussed I've begun to work on this. I thought I'd open this issue:

1. To track it, 
2. To host discussion and 
3. so I could ask some questions...

Namely: is the number of samples (both warmup and total) stored anywhere in the `model_info` attribute of a `greta_mcmc_list` object? I thought it would be saved in the `sampler` class but it doesn't appear to be. I wanted to get it to display it at the top the print method; I think that's useful and it's also what `rstan` does. 

Cheers!

**Comment by goldingn** [comment]
Ooh, good point. No, I don't think it is, but we should add it.

One options which seems tidy would be to put that information into the `mcmc.list` bits of the `greta_mcmc_list` object (both the main draws object of traced parameters and the `raw_draws` object of the free state), via the `start` and `end` parameters. Currently the warmup is ignored so `start(draws)` is 1, and `end(draws)` is `n_samples` (give or take thinning) but it could instead be set up so that start gives `warmup + 1` and end gives warmup + n_samples. I thank that might be what's intended for that class.

Alternatively (or in addition, so you don't need to deal with the effect of thinning), we could just add those bits of information into the `model_info` attribute separately.

**Comment by goldingn** [comment]
That `start` value (of `warmup + 1`) for the post-warmup samples on each chain would have to be passed in through `prepare_draws()` [here](https://github.com/greta-dev/greta/blob/bebbdf5535ca0338fe76226590c8fa76f5f3eb06/R/utils.R#L971-L975) and [here](https://github.com/greta-dev/greta/blob/1190591e94a78937cbc7866067e5c8ea115a472b/R/inference.R#L468-L475)

**Comment by jeffreypullin** [comment]
Right - I've implemented that! (Holding the info in the `mcm.list` objects) Currently I've implemented for the `print` method:

```
> draws
A greta mcmc list object (MCMC draws) 
4 chains, each with 2000 iterations (1000 warmup) with thin = 1
Post-warmup draws per chain = 1000, Total post-warmup draws = 4000
```
I'll have a go at the stuff with variables next

**Comment by jeffreypullin** [comment]
Hi Nick, 

Sorry about the radio silence on this. I somewhat unexpectedly got an RA job for before uni starts and it has unsurprisingly eaten up a lot of my time. 

I'll get to this at some point - just not sure when at this stage.

Cheers, 
Jeffrey

**Comment by goldingn** [comment]
No worries! Congrats on the job, that's great
